<a href="https://colab.research.google.com/github/AngeMervaneJdev/ML_AI_1/blob/main/ml_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importations

In [146]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from random import seed
from random import randrange
from numpy import mean
from numpy import std
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import KFold,cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import SGDRegressor

In [82]:
def scratch_train_test_split(X, y, train_size=0.8):
    """Divide the validation data.

    Parameters
    ----------
    X : ndarray
      Training data (n_samples, n_features)
    y : ndarray
      Correct answer value (n_samples,)
    train_size : float
      Specify what percentage to use as a train (0 < train_size < 1)

    Returns
    -------
    X_train : ndarray
      Training data (n_samples, n_features)
    X_test : ndarray
      Validation data (n_samples, n_features)
    y_train : ndarray
      Correct answer value of training data (n_samples,)
    y_test : ndarray
      Correct value of verification data (n_samples,)
    """
    # Write code here
    X_copy=list(X)
    y_copy=list(y)
    X_train_len=train_size*len(X)
    y_train_len=train_size*len(y)
    
    X_train, X_test, y_train, y_test=list(),list(),list(),list()
    while len(X_train)<X_train_len:
      index=randrange(len(X_copy))
      X_train.append(X_copy.pop(index))
    while len(y_train)<y_train_len:
	   	y_train.append(y_copy.pop(randrange(len(y_copy))))
    X_test,y_test=X_copy,y_copy
    pass
    return X_train, X_test, y_train, y_test

seed(1)
scratch_train_test_split([],[],0.6)

([], [], [], [])

# [Problem 1] Scratch of train_test_split​



## Load iris dataset

In [167]:
data = load_iris()
Y=data.target
X=data.data

dfX=pd.DataFrame(data=X,columns=["sepal_length","sepal_width","petal_length","petal_width"])
dfY=pd.DataFrame(data=Y,columns=["Species"])

df=pd.concat([dfX,dfY],axis=1)
df

sepal_length  sepal_width  petal_length  petal_width  Species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

## test train_test_split scratch

In [168]:
X_train, X_test, y_train, y_test=scratch_train_test_split(X=X,y=Y)

In [169]:
clf = make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3,loss="log"))
clf.fit(X_train, y_train)
print(clf.predict(X_test))

[1 1 1 1 0 1 0 0 1 2 2 0 0 2 0 2 2 0 2 0 0 2 0 2 2 2 0 2 2 2]


## Set 1

In [170]:
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0, cov, n_samples // 2)
f1 = np.random.multivariate_normal(f1, cov, n_samples // 2)
X1 = np.concatenate([f0, f1])
y1 = np.concatenate([
    np.full(n_samples // 2, 1),
    np.full(n_samples // 2, -1)
])

In [171]:
X_train1, X_test1, y_train1, y_test1=scratch_train_test_split(X=X1,y=y1)
print(len(X_train1),len(y_train1))
print("\n\n")
clf = make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3,loss="log"))
clf.fit(X_train1, y_train1)
print(clf.predict(X_test1))

400 400



[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## Set 2

In [172]:
X2 = np.array([
    [-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
    [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
    [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
    [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
    [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
    [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
    [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
    [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
    [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
    [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
    [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
    [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
    [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
    [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
    [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
    [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
    [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
    [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
    [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
    [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ],
])
y2 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [173]:
X_train2, X_test2, y_train2, y_test2=scratch_train_test_split(X=X2,y=y2)
clf = make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3,loss="log"))
clf.fit(X_train2, y_train2)
print(clf.predict(X_test2))

[1 1 1 0 0 1 1 0]


# [Problem 2] Creating a code to solve the classification problem

## Train models

In [174]:
# EVALUATE MODEL USING CROSS_VALIDATION
def evaluate_model(model, X, y):
  cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
  scores=cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise') 
  print("%.3f (%.3f)" % (mean(scores),std(scores)))

### Logistic regression

#### set 2

In [175]:
X_train2, X_test2, y_train2, y_test2=scratch_train_test_split(X=X2,y=y2)
clf = make_pipeline(StandardScaler(),LogisticRegression(max_iter=1000, tol=1e-3))
clf.fit(X_train2, y_train2)
print('Prediction')
print(clf.predict(X_test2))
print('Evaluation')
evaluate_model(LogisticRegression(max_iter=1000, tol=1e-3),X2,y2)

Prediction
[0 0 1 0 1 0 0 0]
Evaluation
0.575 (0.234)


#### set 1

In [176]:
X_train1, X_test1, y_train1, y_test1=scratch_train_test_split(X=X1,y=y1)
clf = make_pipeline(StandardScaler(),LogisticRegression(max_iter=1000, tol=1e-3))
clf.fit(X_train1, y_train1)
print('Prediction')
print(clf.predict(X_test1))
print('Evaluation')
evaluate_model(LogisticRegression(max_iter=1000, tol=1e-3),X1,y1)

Prediction
[ 1  1  1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  1 -1 -1 -1 -1
  1 -1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1  1  1 -1  1 -1  1  1  1  1
  1  1 -1  1  1  1 -1 -1  1  1 -1  1 -1  1  1 -1 -1  1  1  1 -1  1  1  1
  1  1  1  1]
Evaluation
1.000 (0.000)


#### iris dataset

In [177]:
X_train, X_test, y_train, y_test=scratch_train_test_split(X=X,y=Y)
clf = make_pipeline(StandardScaler(),LogisticRegression(max_iter=1000, tol=1e-3))
clf.fit(X_train, y_train)
print('Prediction')
print(clf.predict(X_test))
print('Evaluation')
evaluate_model(LogisticRegression(max_iter=1000, tol=1e-3),X,Y)

Prediction
[1 1 1 0 2 2 2 0 0 1 1 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0]
Evaluation
0.964 (0.041)


### SVM

#### set 2

In [178]:
# TRAINNING AND PREDICTION
X_train2, X_test2, y_train2, y_test2=scratch_train_test_split(X=X2,y=y2)
clf = make_pipeline(StandardScaler(),SVC(gamma='auto'))
clf.fit(X_train2, y_train2)
print('Prediction')
print(clf.predict(X_test2))
print('Evaluation')
evaluate_model(SVC(gamma='auto'),X2,y2)

Prediction
[1 0 1 1 1 0 1 1]
Evaluation
0.700 (0.227)


#### set 1

In [179]:
X_train1, X_test1, y_train1, y_test1=scratch_train_test_split(X=X1,y=y1)
clf = make_pipeline(StandardScaler(),SVC(gamma='auto'))
clf.fit(X_train1, y_train1)
print('Prediction')
print(clf.predict(X_test1))
print('Evaluation')
evaluate_model(SVC(gamma='auto'),X1,y1)

Prediction
[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1]
Evaluation
1.000 (0.000)


#### iris dataset

In [180]:
X_train, X_test, y_train, y_test=scratch_train_test_split(X=X,y=Y)
clf = make_pipeline(StandardScaler(),LogisticRegression(max_iter=1000, tol=1e-3))
clf.fit(X_train, y_train)
print('Prediction')
print(clf.predict(X_test))
print('Evaluation')
evaluate_model(SVC(gamma='auto'),X,Y)

Prediction
[0 0 0 0 0 0 0 0 1 1 0 0 0 0 2 1 0 1 0 0 2 2 2 2 0 2 2 1 2 2]
Evaluation
0.978 (0.031)


### Decision tree

#### set 2

In [181]:
# TRAINNING AND PREDICTION
X_train2, X_test2, y_train2, y_test2=scratch_train_test_split(X=X2,y=y2)
clf = make_pipeline(StandardScaler(),DecisionTreeClassifier())
clf.fit(X_train2, y_train2)
print('Prediction')
print(clf.predict(X_test2))
print('Evaluation')
evaluate_model(DecisionTreeClassifier(),X2,y2)

Prediction
[0 1 1 0 1 0 0 0]
Evaluation
0.683 (0.266)


#### set 1

In [182]:
X_train1, X_test1, y_train1, y_test1=scratch_train_test_split(X=X1,y=y1)
clf = make_pipeline(StandardScaler(),DecisionTreeClassifier())
clf.fit(X_train1, y_train1)
print('Prediction')
print(clf.predict(X_test1))
print('Evaluation')
evaluate_model(DecisionTreeClassifier(),X1,y1)

Prediction
[ 1 -1  1  1 -1  1  1 -1 -1  1 -1  1 -1 -1 -1  1  1  1  1  1 -1  1  1 -1
 -1  1 -1  1 -1  1  1 -1 -1  1 -1  1 -1  1 -1  1  1 -1 -1  1 -1 -1 -1 -1
 -1 -1  1 -1  1 -1  1 -1  1 -1  1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1  1  1
  1  1 -1 -1 -1 -1  1 -1 -1 -1  1  1  1 -1  1  1  1  1 -1 -1 -1 -1 -1 -1
 -1  1 -1  1]
Evaluation
0.998 (0.006)


#### iris dataset

In [183]:
X_train, X_test, y_train, y_test=scratch_train_test_split(X=X,y=Y)
clf = make_pipeline(StandardScaler(),DecisionTreeClassifier())
clf.fit(X_train, y_train)
print('Prediction')
print(clf.predict(X_test))
print('Evaluation')
evaluate_model(DecisionTreeClassifier(),X,Y)

Prediction
[0 2 1 1 0 1 2 2 1 0 1 0 2 1 2 0 1 2 2 1 2 2 1 1 2 1 0 0 1 1]
Evaluation
0.951 (0.054)


#Regression problem

In [197]:
data=pd.read_csv("train.csv")
X=np.array(data[['GrLivArea',"YearBuilt"]])
y=data.SalePrice

In [198]:
X

array([[1710, 2003],
       [1262, 1976],
       [1786, 2001],
       ...,
       [2340, 1941],
       [1078, 1950],
       [1256, 1965]])

In [194]:
y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

# [Problem 3] Creating a code to solve the regression problem

In [206]:
X_train, X_test, y_train, y_test=scratch_train_test_split(X=X,y=y)
reg =SGDRegressor()
reg.fit(X_train, y_train)

reg.score(X_test,y_test)

-1.9782013702053935e+21