<a href="https://colab.research.google.com/github/AngeMervaneJdev/ML_AI_1/blob/main/objectOriented.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Probleme 1\n')
print("Classes are : \n1-DecisionTreeRegressor\nStandardScaler\n")

# Classe: StandardScaler
* Methods:

   + fit()
   + transform()
   + fit_transform()
   + partial_fit()
   + set_params()

* Variables:
  
   + mean_
   + var_
   + feature_names_in_
   + n_features_in_
   + scale_


In [4]:
print("Probleme 3\n")
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        Moyenne
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のためにMoyenneと標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """

        self.mean_ = np.mean(X,axis=0 )
        self.var_ = np.var(X,axis=0)
        return self
        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特徴量
        """
        X_scaled=(X - self.mean_) / np.sqrt(self.var_) # np.sqrt(self.var_)=self.scale_
        pass
        return X_scaled


import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("Moyenne : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)


Probleme 3

Moyenne : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [15]:
print('Probleme \n')
class BasicsOperations():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):

        """
        受け取った引数をself.valueに加える
        """
        self.check_params_validity(value2)
        self.value += value2
    def division(self,value2):
        self.check_params_validity(value2)
        if value2!=0:
          self.value/=value2
        else:
          raise ZeroDivisionError("Le diviseur ne doit pas être nule")
    def subtraction(self,value2):
          self.check_params_validity(value2)
          self.value-=value2
    
    def multiplication(self,value2):
          self.check_params_validity(value2)
          self.value*=value2

    def check_params_validity(self,value2):
        if type(value2)==str or type(value2)==list: 
          raise ValueError("The parameter type should not be array or string !!")
        else:
          pass
       

example = BasicsOperations(5)
print("Initial value : {}".format(example.value))
example.add(3)
print("Addiction (3) --> Value : {}".format(example.value))
example.multiplication(15)
print("Multiplication (15) --> Value : {}".format(example.value))
example.division(2)
print("Division --> Value : {}".format(example.value))
example.subtraction(15)
print("Substraction --> Value : {}".format(example.value))

print('Tray adding string to value, will raise error !! :) ')
example.add('salut')

Probleme 

初期値5が設定されました
Initial value : 5
Addiction (3) --> Value : 8
Multiplication (15) --> Value : 120
Division --> Value : 60.0
Substraction --> Value : 45.0
Tray adding string to value, will raise error !! :) 


ValueError: ignored