<a href="https://colab.research.google.com/github/AngeMervaneJdev/ML_AI_1/blob/main/produitmatrice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Procédé de calcul matricielle (A*B)
* Verifier si le nombre de colonnes de A (n_col_A) est égal au nombre de lignes de B (n_ligne_B)
* Si n_col_A=n_ligne_B on precède au calcul
   - on prend la premiere ligne de A (A1k) et on prend la premiere colonne de B (B11) avec ( i elément de [ 1..taille_ligne_0_de_A ]  et k elément de [ 1..taille_ligne_0_de_A ] )
   -on multiplie chaque élément de A1i avec chaque élément de Bi1 (soit B11,B12,B13 ..), puis on fait leur somme. cette somme représente un élément d'une ligne de la matrice resultante M (M=A*B)
   -on ajoute cette somme à une ligne de M puis on passe à la colonne suivante de B. Ainsi de suite pour remplir la premiere ligne de M
   -apres la formation de la premiere ligne on passe à la seconde ligne de A et on fait la somme cumullée des A2k*Bi1 pour i allant de 1 à taille_ligne_0_de_A
   Ainsi de suite jusqu'à se qu'on parcours toutes les ligne de A

*En gros on prend une ligne de A et on multiplie chaque élément avec chaque élément de chaque colonne de B, la somme des produits obtenu à chaque colonne represente un élément d'une ligne de la matrice M




In [1]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

m = []
for i in range(len(a_ndarray)):

  ligne = [] # tableau de chaque ligne 

  # on multiplie les elements sur uen ligne de A avec tout les elements sur une colonne de B

  for j in range(len(b_ndarray[0])):  #(len(b_ndarray[0])=3

    element = 0   # somme des Aik*Bkj par ligne de A et colonne de B
    for k in range(len(a_ndarray[0])):

      element = element + a_ndarray[i][k] * b_ndarray[k][j]

       # on mettient la ligne de Ai(fixe)k(1-3) et on parcours la colonne de B avec le numéro de ligne qui varie

    ligne.append(element) 

    #ajout d'un element d'une ligne de la matrise resultante 
    #element suivant

  m.append(ligne) # ajout de la ligne et passage vers la mise en place de la ligne suivante
print(m)

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]


In [2]:
print("Probleme 2\n")

import numpy as np
print(a_ndarray.dot(b_ndarray))

Probleme 2

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [ ]:
print("Probleme 3\n")
import numpy as np 
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

def maxt_product(a,b):
  somme,i=0,0
  for j in range(len(a_ndarray)):
    somme+=a_ndarray[i][j]*b_ndarray[j][i]
  print(somme)
maxt_product(a_ndarray,b_ndarray)


Probleme 3

6


In [ ]:
print("Probleme 4\n")
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

def mulMat(mat_a,mat_b):
  somme,i=0,0
  matrice=[]
  for k in range(len(mat_a[0])):
    ligne=[]
    for i in range(len(mat_a[0])):
      somme=0
      for j in range(len(mat_a[0])):
        somme+=mat_a[k][j]*mat_b[j][i]
      ligne.append(somme)
    matrice.append(ligne)
  return matrice
print(mulMat(a_ndarray,b_ndarray))
    

Probleme 4

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]


In [ ]:
print("Probleme 5\n")
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1],[2, 9, -1]])

def mulMat(mat_a,mat_b):
  if len(mat_a[0]) != len(mat_b):
    print("erreur le nombre de colonnes de la premier matrice doit être égal au nombre de ligne de la seconde matrice")
    return False
  somme,i=0,0
  matrice=[]
  for k in range(len(mat_a[0])):
    ligne=[]
    for i in range(len(mat_a[0])):
      somme=0
      for j in range(len(mat_a[0])):
        somme+=mat_a[k][j]*mat_b[j][i]
      ligne.append(somme)
    matrice.append(ligne)
  return matrice
print(mulMat(a_ndarray,b_ndarray))
   

Probleme 5

erreur le nombre de colonnes de la premier matrice doit être égal au nombre de ligne de la seconde matrice
False


In [ ]:
print("Probleme 6\n")
import numpy as np
print(mulMat(a_ndarray,b_ndarray.T))

Probleme 6

[[7, -20, 13], [-4, -58, -43], [7, 88, 95]]
